name: Bump dependencies
on:
    workflow_dispatch:
    schedule:
        - cron: 45 19 * * * # 60 min before Dependabot
    push:
        paths:
            - package.json
            - package-lock.json
            - .github/workflows/bump.yml
        branches:
            - main

permissions: write-all

jobs:
    bump:
        name: Bump
        runs-on: ubuntu-20.04
        concurrency: bump-group

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Setup Node.JS
              uses: actions/setup-node@v4.1.0
              with:
                  node-version: 18.11.0
                  cache: npm

            - name: Bump
              id: sync_types
              uses: RedGuy12/sync-types@v2.1.1

            - name: Commit
              id: commit
              uses: peter-evans/create-pull-request@v7.0.5
              with:
                  token: ${{ secrets.TOKEN }}
                  author:
                      github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
                  commit-message: Bump dependencies
                  branch: ci-bump-dependencies
                  delete-branch: true
                  title: Bump dependencies
                  body-path: ${{ steps.sync_types.outputs.output-dir }}/output.md
