name: Label PRs
on: pull_request_target

jobs:
    label:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        steps:
            - name: Fetch metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2.2.0
              with:
                  skip-verification: true
            - name: Checkout
              uses: actions/checkout@v4.2.2
              with:
                  ref: ${{ github.head_ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
            - name: Add labels
              run:
                  gh pr edit ${{ github.event.pull_request.number }} --add-label
                  "${{steps.metadata.outputs.dependency-type}},${{steps.metadata.outputs.update-type}}"
              env:
                  GITHUB_TOKEN: ${{secrets.TOKEN}}
